# Generated by Django 3.1.5 on 2021-01-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skus',
            unique_together={('sku', 'mfg')},
        ),
    ]
