# Generated by Django 3.1.5 on 2021-01-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_hr', '0002_auto_20210122_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passangers',
            new_name='Passengers',
        ),
    ]
