# Generated by Django 3.1.5 on 2021-01-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_hr', '0003_auto_20210122_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passengers',
            new_name='Passenger',
        ),
    ]
