# Generated by Django 3.1.5 on 2021-01-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_hr', '0004_auto_20210122_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='passenger',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
