# Generated by Django 3.1.5 on 2021-01-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_hr', '0005_auto_20210125_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='ssn',
            field=models.IntegerField(default=0),
        ),
    ]
