# Generated by Django 3.1.5 on 2021-01-26 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_hr', '0006_passenger_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='first',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'must be 2 characters or more.')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'must be 2 characters or more.')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='password',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator('^(?=.{8,}$)(?=.*[A-Z]).*$', 'Password must be at least 8 characters with 1 being a Capital Letter.')]),
        ),
    ]
